# Alembic migration script template.
#
# This is a simplified version of the default Alembic template.

revision = '7446ee532bce'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


def upgrade() -> None:
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_cols = {c['name'] for c in inspector.get_columns('quiz_attempts')}
    if 'answer_text' not in existing_cols:
        op.add_column('quiz_attempts', sa.Column('answer_text', sa.Text(), nullable=True))
    if 'score' not in existing_cols:
        op.add_column('quiz_attempts', sa.Column('score', sa.Float(), nullable=False, server_default=sa.text('0')))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_attempts', 'score')
    op.drop_column('quiz_attempts', 'answer_text')
    # ### end Alembic commands ###
